/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author kevrodriguez
 */
public class frmServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Servicio
     */
    public frmServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServicio = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblUser18 = new javax.swing.JLabel();
        txtEmpleado2 = new javax.swing.JTextField();
        lblUser19 = new javax.swing.JLabel();
        btnBuscarEmpleado3 = new javax.swing.JButton();
        cbEstado2 = new javax.swing.JComboBox<>();
        lblUser20 = new javax.swing.JLabel();
        calendarFecha2 = new com.toedter.calendar.JCalendar();
        lblUser21 = new javax.swing.JLabel();
        txtTotalPago2 = new javax.swing.JTextField();
        lblUser22 = new javax.swing.JLabel();
        lblUser23 = new javax.swing.JLabel();
        lblUser24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        paneDescripción2 = new javax.swing.JTextPane();
        btnRecargar9 = new javax.swing.JButton();
        btnRecargar10 = new javax.swing.JButton();
        btnRecargar11 = new javax.swing.JButton();
        btnRecargar12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblUser7 = new javax.swing.JLabel();
        cbBuscarEstado = new javax.swing.JComboBox<>();
        btnBuscarEstado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbBuscarEstado1 = new javax.swing.JComboBox<>();
        lblUser10 = new javax.swing.JLabel();
        btnBuscarEstado1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEmpleados1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(40, 40, 40));
        jTabbedPane1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableServicio.setBackground(new java.awt.Color(244, 244, 244));
        tableServicio.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        tableServicio.setForeground(new java.awt.Color(40, 40, 40));
        tableServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Trabajador", "Estado", "Fecha Inicio", "Total Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableServicio);
        if (tableServicio.getColumnModel().getColumnCount() > 0) {
            tableServicio.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableServicio.getColumnModel().getColumn(0).setMaxWidth(75);
        }

        jPanel5.setBackground(new java.awt.Color(0, 47, 119));

        lblUser18.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser18.setForeground(new java.awt.Color(255, 255, 255));
        lblUser18.setText("Empleado:");

        txtEmpleado2.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpleado2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtEmpleado2.setForeground(new java.awt.Color(40, 40, 40));
        txtEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpleadoActionPerformed(evt);
            }
        });

        lblUser19.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser19.setForeground(new java.awt.Color(255, 255, 255));
        lblUser19.setText("Estado:");

        btnBuscarEmpleado3.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Servicio/btnBuscarUsuario.png"))); // NOI18N
        btnBuscarEmpleado3.setBorder(null);
        btnBuscarEmpleado3.setBorderPainted(false);
        btnBuscarEmpleado3.setContentAreaFilled(false);
        btnBuscarEmpleado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleado1ActionPerformed(evt);
            }
        });

        cbEstado2.setBackground(new java.awt.Color(255, 255, 255));
        cbEstado2.setForeground(new java.awt.Color(40, 40, 40));
        cbEstado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Proceso", "Completado", "Cancelado" }));

        lblUser20.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser20.setForeground(new java.awt.Color(255, 255, 255));
        lblUser20.setText("Fecha");

        calendarFecha2.setBackground(new java.awt.Color(255, 255, 255));
        calendarFecha2.setForeground(new java.awt.Color(40, 40, 40));

        lblUser21.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser21.setForeground(new java.awt.Color(255, 255, 255));
        lblUser21.setText("Total a");

        txtTotalPago2.setBackground(new java.awt.Color(244, 244, 244));
        txtTotalPago2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtTotalPago2.setForeground(new java.awt.Color(40, 40, 40));
        txtTotalPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagoActionPerformed(evt);
            }
        });

        lblUser22.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser22.setForeground(new java.awt.Color(255, 255, 255));
        lblUser22.setText("pagar");

        lblUser23.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser23.setForeground(new java.awt.Color(255, 255, 255));
        lblUser23.setText("Inicio");

        lblUser24.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lblUser24.setForeground(new java.awt.Color(255, 255, 255));
        lblUser24.setText("Descripción:");

        paneDescripción2.setBackground(new java.awt.Color(255, 255, 255));
        paneDescripción2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        paneDescripción2.setForeground(new java.awt.Color(40, 40, 40));
        jScrollPane5.setViewportView(paneDescripción2);

        btnRecargar9.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Usuarios/btnAgregar.png"))); // NOI18N
        btnRecargar9.setBorder(null);
        btnRecargar9.setBorderPainted(false);
        btnRecargar9.setContentAreaFilled(false);
        btnRecargar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargar1ActionPerformed(evt);
            }
        });

        btnRecargar10.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Servicio/btnActualizarEstado.png"))); // NOI18N
        btnRecargar10.setBorder(null);
        btnRecargar10.setBorderPainted(false);
        btnRecargar10.setContentAreaFilled(false);
        btnRecargar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargar2ActionPerformed(evt);
            }
        });

        btnRecargar11.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Usuarios/btnRecargar.png"))); // NOI18N
        btnRecargar11.setBorder(null);
        btnRecargar11.setBorderPainted(false);
        btnRecargar11.setContentAreaFilled(false);
        btnRecargar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargar3ActionPerformed(evt);
            }
        });

        btnRecargar12.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Usuarios/btnEliminar.png"))); // NOI18N
        btnRecargar12.setBorder(null);
        btnRecargar12.setBorderPainted(false);
        btnRecargar12.setContentAreaFilled(false);
        btnRecargar12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser20)
                            .addComponent(lblUser23))
                        .addGap(18, 18, 18)
                        .addComponent(calendarFecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUser21)
                            .addComponent(lblUser22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUser24)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblUser18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarEmpleado3)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecargar9)
                .addGap(18, 18, 18)
                .addComponent(btnRecargar10)
                .addGap(18, 18, 18)
                .addComponent(btnRecargar11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecargar12)
                .addGap(59, 59, 59))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUser18))
                            .addComponent(btnBuscarEmpleado3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser19)
                            .addComponent(cbEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lblUser20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser23))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblUser21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUser22)))))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendarFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblUser24)
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRecargar9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecargar10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecargar11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRecargar12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Servicio/logoServicio.png"))); // NOI18N

        lblUser7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblUser7.setForeground(new java.awt.Color(40, 40, 40));
        lblUser7.setText("Buscar Servicio por Estado");

        cbBuscarEstado.setBackground(new java.awt.Color(244, 244, 244));
        cbBuscarEstado.setForeground(new java.awt.Color(40, 40, 40));
        cbBuscarEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Proceso", "Completado", "Cancelado" }));

        btnBuscarEstado.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Inventario/btnBuscar.png"))); // NOI18N
        btnBuscarEstado.setBorder(null);
        btnBuscarEstado.setBorderPainted(false);
        btnBuscarEstado.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbBuscarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarEstado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbBuscarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(btnBuscarEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12))))
        );

        jTabbedPane1.addTab("Servicio", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cbBuscarEstado1.setBackground(new java.awt.Color(244, 244, 244));
        cbBuscarEstado1.setForeground(new java.awt.Color(40, 40, 40));
        cbBuscarEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Proceso", "Completado", "Cancelado" }));

        lblUser10.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblUser10.setForeground(new java.awt.Color(40, 40, 40));
        lblUser10.setText("Buscar Servicio por Estado");

        btnBuscarEstado1.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarEstado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Inventario/btnBuscar.png"))); // NOI18N
        btnBuscarEstado1.setBorder(null);
        btnBuscarEstado1.setBorderPainted(false);
        btnBuscarEstado1.setContentAreaFilled(false);
        btnBuscarEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstado1ActionPerformed(evt);
            }
        });

        tableEmpleados1.setBackground(new java.awt.Color(244, 244, 244));
        tableEmpleados1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        tableEmpleados1.setForeground(new java.awt.Color(40, 40, 40));
        tableEmpleados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Trabajador", "Estado", "Fecha", "Total Pago", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableEmpleados1);
        if (tableEmpleados1.getColumnModel().getColumnCount() > 0) {
            tableEmpleados1.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableEmpleados1.getColumnModel().getColumn(0).setMaxWidth(75);
            tableEmpleados1.getColumnModel().getColumn(5).setPreferredWidth(400);
        }

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/Servicio/logoServicio.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel6)
                .addGap(463, 463, 463))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUser10)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(cbBuscarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarEstado1)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblUser10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBuscarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver Servicio", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEstado1ActionPerformed

    private void btnRecargar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargar4ActionPerformed

    private void btnRecargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargar3ActionPerformed

    private void btnRecargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargar2ActionPerformed

    private void btnRecargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargar1ActionPerformed

    private void txtTotalPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagoActionPerformed

    private void btnBuscarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEmpleado1ActionPerformed

    private void txtEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado3;
    private javax.swing.JButton btnBuscarEstado;
    private javax.swing.JButton btnBuscarEstado1;
    private javax.swing.JButton btnRecargar10;
    private javax.swing.JButton btnRecargar11;
    private javax.swing.JButton btnRecargar12;
    private javax.swing.JButton btnRecargar9;
    private com.toedter.calendar.JCalendar calendarFecha2;
    private javax.swing.JComboBox<String> cbBuscarEstado;
    private javax.swing.JComboBox<String> cbBuscarEstado1;
    private javax.swing.JComboBox<String> cbEstado2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUser10;
    private javax.swing.JLabel lblUser18;
    private javax.swing.JLabel lblUser19;
    private javax.swing.JLabel lblUser20;
    private javax.swing.JLabel lblUser21;
    private javax.swing.JLabel lblUser22;
    private javax.swing.JLabel lblUser23;
    private javax.swing.JLabel lblUser24;
    private javax.swing.JLabel lblUser7;
    private javax.swing.JTextPane paneDescripción2;
    private javax.swing.JTable tableEmpleados1;
    private javax.swing.JTable tableServicio;
    private javax.swing.JTextField txtEmpleado2;
    private javax.swing.JTextField txtTotalPago2;
    // End of variables declaration//GEN-END:variables
}
